In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [4]:
#GET THE DATA
dataset = pd.read_csv('Churn_Modelling.csv')

#FEATURES; ALL EXCEPT ROWNUMBER; CUSTOMERID; SURNAME; LABEL [2 to -2]
X = dataset.iloc[:,3:-1].values
Y = dataset.iloc[:, -1].values

In [6]:
#ENCODING CATEGORICAL DATA
#-> COUNTRY [FRANCE, SPAIN, GERMANY]
#-> GENDER [FEMALE, MALE]
#CONVERT TO LABELS (0,1) OR ONE-HOT ENCODING

In [7]:
#LABEL ENCODING OF GENDER [0,1]
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#->ALL ROWS; ONLY COLUMN WITH INDEX 2
X[:,2] = le.fit_transform(X[:,2])
#[MALE,FEMALE] -> [0,1]

/Users/kpandey/anaconda3/envs/nlp_course/lib/python3.7/site-packages/sklearn/utils/validation.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  LARGE_SPARSE_SUPPORTED = LooseVersion(scipy_version) >= '0.14.0'


In [15]:
#ONE-HOT ENCODING OF GEOGRAPHY [NO RELATION BETWEEN FRANCE, GERMANY, SPAIN]
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#->COLUMN WITH INDEX 1
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

/Users/kpandey/anaconda3/envs/nlp_course/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:351: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = check_array(X, dtype=np.int)
/Users/kpandey/anaconda3/envs/nlp_course/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:95: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to speci

In [16]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [47]:
#SPLIT DATASET INTO TRAINING AND TEST SET
from sklearn.model_selection import train_test_split
X_TRAIN, X_TEST, Y_TRAIN, Y_TEST = train_test_split(X, Y, test_size= 0.2, random_state = 42)

In [48]:
#FEATURE SCALING - NECESSARY FOR DEEP LEARNING
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_TRAIN = sc.fit_transform(X_TRAIN)
X_TEST = sc.transform(X_TEST) #AVOID INFORMATION LEAKAGE; NO FIT

/Users/kpandey/anaconda3/envs/nlp_course/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/Users/kpandey/anaconda3/envs/nlp_course/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/Users/kpandey/anaconda3/envs/nlp_course/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [21]:
#BUILDING THE ARTIFICIAL NEURAL NETWORK

In [23]:
#INITIALISING THE ANN
from tensorflow.keras.models import Sequential

ann = Sequential()

In [24]:
#ADDING INPUT AND FIRST HIDDEN LAYER

#DENSE TO ADD A SIMPLE FULLY CONNECTED LAYER
from tensorflow.keras.layers import Dense

#DROPOUT LAYER TO AVOID OVERFITTING


#->UNITS = NUMBER OF NEURONS IN HIDDEN LAYER
#-> HOW MANY NEURONS? EXPERIMENTATION; NO RULE OF THUMB [THESE ARE HYPERPARAMETERS]
#-> HIDDEN LAYERS HAVE RECTIFIER FUNCTION
ann.add(Dense(units= 6, activation = 'relu'))

In [25]:
#ADDING SECOND HIDDEN LAYER
ann.add(Dense(units= 6, activation = 'relu'))

In [26]:
#ADDING OUTPUT LAYER

#-> FULLY CONNECTED: DENSE
#-> OUTPUT LAYER; NUMBER OF NEURONS = 1; BINARY CLASSIFICATION
#-> OUTPUT LAYER; ACTIVATION = SIGMOID
ann.add(Dense(units= 1, activation = 'sigmoid')) #PROBABILITIES ALSO

In [27]:
#COMPILING THE ANN
#-> BEST OPTIMIZER: SDG; ADAM PERFORMS SDG
#-> BINARY CLASSIFICATION; BINARY_CROSSENTROPY
#-> NON BINARY CLASSIFICATION: CATEGORICAL_CROSSENTROPY; ACTIVATION. ='SOFTMAX', MULTIPLE NEUROONS IN OUTPUT LAYER
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [59]:
#TRAINING THE ANN ON TRAINING SET
#->BATCH TRAINING MORE EFFICIENT
#->GOOD AMOUNT OF EPOCHS FOR BETTER LEARNING
ann.fit(X_TRAIN, Y_TRAIN, epochs=200, verbose=1, batch_size=32)

Epoch 1/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3248 - accuracy: 0.8650
Epoch 2/200
250/250 [==============================] - 0s 992us/step - loss: 0.3251 - accuracy: 0.8643
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3246 - accuracy: 0.8646
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3248 - accuracy: 0.8629
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3245 - accuracy: 0.8644
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3243 - accuracy: 0.8648
Epoch 7/200
250/250 [==============================] - 0s 943us/step - loss: 0.3245 - accuracy: 0.8637
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3245 - accuracy: 0.8639
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3245 - accuracy: 0.8644
Epoch 10/200
250/250 [==============================] - 0s 971us/step - loss: 0.3244 - 

250/250 [==============================] - 0s 1ms/step - loss: 0.3241 - accuracy: 0.8631
Epoch 81/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3243 - accuracy: 0.8637
Epoch 82/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3244 - accuracy: 0.8641
Epoch 83/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3244 - accuracy: 0.8645
Epoch 84/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3242 - accuracy: 0.8630
Epoch 85/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3243 - accuracy: 0.8639
Epoch 86/200
250/250 [==============================] - 0s 996us/step - loss: 0.3245 - accuracy: 0.8650
Epoch 87/200
250/250 [==============================] - 0s 944us/step - loss: 0.3242 - accuracy: 0.8637
Epoch 88/200
250/250 [==============================] - 0s 908us/step - loss: 0.3245 - accuracy: 0.8640
Epoch 89/200
250/250 [==============================] - 0s 911us/step - loss: 0.3244 - ac

250/250 [==============================] - 0s 965us/step - loss: 0.3238 - accuracy: 0.8644
Epoch 159/200
250/250 [==============================] - 0s 986us/step - loss: 0.3242 - accuracy: 0.8639
Epoch 160/200
250/250 [==============================] - 0s 880us/step - loss: 0.3244 - accuracy: 0.8643
Epoch 161/200
250/250 [==============================] - 0s 909us/step - loss: 0.3239 - accuracy: 0.8644
Epoch 162/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3236 - accuracy: 0.8656
Epoch 163/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3240 - accuracy: 0.8635
Epoch 164/200
250/250 [==============================] - 0s 907us/step - loss: 0.3240 - accuracy: 0.8640
Epoch 165/200
250/250 [==============================] - 0s 900us/step - loss: 0.3239 - accuracy: 0.8629
Epoch 166/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3240 - accuracy: 0.8643
Epoch 167/200
250/250 [==============================] - 0s 1ms/step - loss

In [36]:
#MAKE A PREDICTION

#TESTING DATA
data = [[1,0,0,600,1,40,3,60000,2,1, 1,50000]]

#SCALING
data_scaled = sc.transform(data)

data_scaled

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
prediction = ann.predict(data_scaled.tolist())

1/1 [==============================] - 0s 111ms/step


In [39]:
prediction

array([[0.09351724]], dtype=float32)

In [43]:
#CONVERT TO FINAL PREDICTION

Threshold = 0.5
prediction = prediction > Threshold
print(prediction)

[[False]]


In [49]:
#PREDICTING TEST
predictions = ann.predict(X_TEST)

63/63 [==============================] - 0s 1ms/step


In [51]:
#PRINT REAL RESULT AND PREDICTED
predictions = (predictions>0.5)
print(np.concatenate((predictions.reshape(len(predictions),1), Y_TEST.reshape(len(Y_TEST),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 1]
 [0 1]]


In [56]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(Y_TEST, predictions))
print(accuracy_score(Y_TEST, predictions))

              precision    recall  f1-score   support

           0       0.89      0.96      0.92      1607
           1       0.73      0.50      0.59       393

   micro avg       0.87      0.87      0.87      2000
   macro avg       0.81      0.73      0.76      2000
weighted avg       0.86      0.87      0.86      2000

0.8655


In [58]:
type(X_TRAIN)

numpy.ndarray